### ISSUE TITLE
items with descriptions set in there meta data do not show up in crafting guide

### ISSUE THREAD

**Issue by wsor4035** [minetest-mods/i3#21]
as found here, https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2040-L2041 you can set a description into a craft, however i3 does not show this and instead shows the description from the items registration, this does show properly when you go to craft the item

**Comment by kilbith** [comment]
Wrong. You can set a metadata into an itemstack, not a craft definition. Regular craft definition doesn't consider item's metadata.

**Comment by wsor4035** [comment]
output = itemstack_var:to_string() in the crafting recipe, this is how hardware coloring works for crafting recipes https://github.com/minetest/minetest/pull/5870. anyways, this doesnt matter as my copy of i3 was a few commits behind and it has since been fixed

**Comment by kilbith** [comment]
I'm not sure `minetest.register_craft` accepts an ItemStack with metadata as output field.

**Comment by kilbith** [comment]
Ah, ok. This PR speaks me more.

**Comment by wsor4035** [comment]
![image](https://user-images.githubusercontent.com/24964441/114248975-384a3280-9967-11eb-8a37-06589c8a39a3.png)
![image](https://user-images.githubusercontent.com/24964441/114248992-4304c780-9967-11eb-8ede-88d3495922e9.png)
https://github.com/wsor4035/i3_color_demo/blob/master/init.lua#L48-L57 demo added

**Comment by kilbith** [comment]
https://github.com/minetest-mods/i3/commit/173f03dc8177ab25d1d541103d0c87d495d79048

**Comment by wsor4035** [comment]
Thank you

**Comment by kilbith** [comment]
This commit enables displaying items with hardware coloring in the crafting guide (`color` metadata): https://github.com/minetest-mods/i3/commit/ed98db0e58452a49e700380b160f68bcd5841815

**Comment by wsor4035** [comment]
interesting, updated in a project im working on, and it crashes with i3\init.lua:1473: unexpected symbol near '<'` however with mtg in the test mod, it works fine. I will have to look into this tommorrow

**Comment by kilbith** [comment]
There is no `<` on line 1473.

**Comment by wsor4035** [comment]
i know, thats what is odd

**Comment by wsor4035** [comment]
fixed, git had issues

**Comment by kilbith** [comment]
That was likely a conflict and you forgot to remove the `<<<<<<`

**Comment by wsor4035** [comment]
yeah
